baseURL = "https://stephan-rayner.github.io/"
languageCode = "en-us"
title = "Stephan Rayner"
theme="hugo-PaperMod"

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[params]
author = "Stephan Rayner"

  [params.homeInfoParams]
  Title = "My Mostly Technical Personal Blog"
  Content = """
👋 Welcome to my personal blog!

At its heart, this blog is about three things: preserving the wisdom passed to me, refining my understanding through explanation, and inviting others into the messy joy of figuring things out together. It’s for them, and for me. 🌱
"""

  [[params.socialIcons]]
  name = "github"
  title = "Find me on Github"
  url = "https://github.com/stephan-rayner"

  [[params.socialIcons]]
  name = "linkedin"
  title = "Find me on Linkedin"
  url = "https://linkedin.com/in/stephanrayner"

  [[params.socialIcons]]
  name = "gitlab"
  title = "Find me on GitLab"
  url = "https://gitlab.com/srayner/funcgraph/"