baseURL = "https://stephan-rayner.github.io/"
languageCode = "en-us"
title = "Stephan Rayner"
theme="hugo-PaperMod"

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[params]
author = "Stephan Rayner"
description = "Mostly technical blog of Stephan Rayner"
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = false  # collapsed by default
ShowReadingTime = true
ShowWordCount = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
defaultTheme = "auto"
enableRobotsTXT = true

[params.editPost]
URL = "https://github.com/stephan-rayner/blog/blob/main/stephan-rayner/content"
Text = "Suggest Changes"
appendFilePath = true

[params.profileMode]
enabled = true
title = "Stephan Rayner"
subtitle = "Mostly technical writing about databases, tools, and dev experience"
imageUrl = "images/avatar.jpg"
imageTitle = "Stephan Rayner"

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

  [[params.profileMode.buttons]]
  name = "Tags"
  url = "/tags"

  [[params.socialIcons]]
  name = "github"
  title = "Find me on Github"
  url = "https://github.com/stephan-rayner"

  [[params.socialIcons]]
  name = "linkedin"
  title = "Find me on Linkedin"
  url = "https://linkedin.com/in/stephanrayner"

  [[params.socialIcons]]
  name = "gitlab"
  title = "Find me on GitLab"
  url = "https://gitlab.com/srayner/funcgraph/"
